### ISSUE TITLE
Non forcing Github 2FA?

### ISSUE THREAD

**Issue by tunnckoCore** [conventional-commits/meta#3]
Hey, i just left the org before few weeks because of that.
Is it big deal for you guys or not? I really don't find much sense in 2FA and disabled in most of the places. It definitely isn't "more secure", in reality, it might even be more insecure because it's easier to get 2FA code than breaking some huge random generated password.

In any way, if you don't want to consider that, re-invite me again and I'll sadly re-activate it... ;/

I want to be part of the org and already created huge work on that topic in last months, so I can transfer a couple of my repos here. 

[parse-commit-message v3](https://github.com/tunnckoCore/parse-commit-message/tree/next/) is on its way too. From now on, it can be called "conventional commits utils" for sure. It can parse, stringify **and** validate (both objects and strings) against the specification.

I also created [git-commits-since](https://github.com/tunnckoCoreLabs/git-commits-since), [recommended-bump](https://github.com/tunnckoCoreLabs/recommended-bump) and [detect-next-version](https://github.com/tunnckoCoreLabs/detect-next-version) as part of the greater good in automation.

**Comment by tunnckoCore** [comment]
damn, how this duplication of both issues happened?! :D

**Comment by tunnckoCore** [comment]
cc @stevemao @damianopetrungaro

**Comment by damianopetrungaro** [comment]
Sorry just noticed.
Why can it be less secure?

**Comment by tunnckoCore** [comment]
Here are a few examples: https://blog.malwarebytes.com/101/2018/09/two-factor-authentication-2fa-secure-seems/

Anyway, I just don't like it unless it's email based. I'm all in with LastPass which helps a lot and simplifies the login flow - I just don't know and don't care what are my passwords. They are strong enough, because it generates 50+ mixed symbols passwords. Even before using such managers I still had 60+ symbol passwords anyway.

**Comment by hutson** [comment]
Howdy,

I would like to contribute to this discussion as well, partly because I'm passionate about protecting software consumers, but also because I'm the person directly responsible for enabling the 2FA feature for this organization.

You brought up two points with our 2FA policy, both of which I want to re-state here to make sure I heard them correctly:
- Requiring a 2FA token reduces the security of the login and authentication process.
- 2FA is unnecessary when using a complex password.

Let me address the first point. Assuming a 2FA user continues to use the same password practices before and after adopting 2FA, then the use of 2FA should be no _less_ secure. However, let's assume the token is acquired by an attacker. If the user is using the same password practices, then the attacker would still need to discover the user's password. Therefore it would be the same situation as if 2FA was not enabled.

As for your second point, I would like to say that I appreciate how you're using a long, complex, password for your GitHub account. Unfortunately not all GitHub users use long, complex, passwords. I
suspect many GitHub users also reuse the same password across multiple websites as well. Without 2FA, the code within this organization would be as safe as the weakest password practice used by a member of the organization. To mitigate that risk we enabled 2FA. Now this organization's code is as safe as the weakest password practice **and** 2FA device.

As for the security of 2FA, it's known that [SMS-based tokens may be intercepted](https://www.securityweek.com/nist-denounces-sms-2fa-what-are-alternatives), and other [token-based methods](https://isc.sans.edu/diary/Phishing+Attempts+That+Bypass+2FA/24446) can be compromised through phishing. It's why hardware-based 2FA devices are [considered by some as an ideal 2FA method](https://arstechnica.com/information-technology/2016/12/this-low-cost-device-may-be-the-worlds-best-hope-against-account-takeovers/).

**Comment by tunnckoCore** [comment]
> - Requiring a 2FA token reduces the security of the login and authentication process.

I'm not saying that. Saying that it might not be more secure and there are breaches that prove that fact as your pointed it.

> Assuming a 2FA user continues to use the same password practices before and after adopting 2FA, then the use of 2FA should be no _less_ secure. However, let's assume the token is acquired by an attacker. If the user is using the same password practices, then the attacker would still need to discover the user's password. Therefore it would be the same situation as if 2FA was not enabled.

Yes.

> - 2FA is unnecessary when using a complex password.

Not exactly. 

> As for your second point

Yea, I understand. 

But:

1. isn't the teams for that? So not everyone will be an owner or having so big permissions to takedown the org.
2. members of this or conventional-changelog orgs are not just some casual devs or code monkeys, there are here in the Node.js community for years, and I don't think there is someone who put his account at risk and uses weak passwords or reuses same passwords. 
3. there is github orgs that all members are owners, and that's okey. But to be owner that means responsibilities and also that someone or all of the other members have trust in you in the first place anyway. To get trust you should respect what you are doing and doing it great, and so to care at least for your github account.
4. Even if everyone is having 2FA enabled in GitHub, it not means he uses the "using app" method instead of the "using SMS", so org can still be available for attack if the attacker attack user that uses the 2FA SMS method. 

All I'm saying is that it's not guaranteed it is "more secure" when requiring 2FA to be enabled. 

#### Unless:
GitHub allow more fine tuing of that option for orgs - e.g. require 2FA **AND** require 2FA to be "Using app" not "using sms" method. Feature that should be suggested to them. Or at least another feature: require 2FA for certain team(s). Only then it will be "more secure" than any other approach.

https://twitter.com/tunnckoCore/status/1076246391171764224

> As for the security of 2FA, it's known that 

Exactly.

***

When a user decides to start using tools like LastPass he definitely should change his password and rely on the auto-generated ones. I don't know what percentage of the users do it that way. I really hope they doing it that way - I did, deleted the whole account history, passwords, and bookmarks from google and switched all the passwords to generated ones for all sites that I can think of and use the most (~50-100? ;d).

**Comment by damianopetrungaro** [comment]
What if LastPass has a security issue?
Using a 2FA is the only option you have to be even more secure.

**Comment by tunnckoCore** [comment]
Agree.

**Comment by bcoe** [comment]
@tunnckoCore 👋 ideally I'd like to keep 2FA enabled... I'm honestly tempted to enable this setting on a few more orgs I'm involved with.

The value of 2FA is that it forces two things:

1. something that you know (your password).
2. something you have with you, your yubikey, your phone, etc.

Folks leak their password all the time:

* they record their screen for a blog post with their password being typed in.
* they accidentally publish their `.bash_history` to Github with their dot files.
* they use a password early on when creating a project, and forget that it remains in the git history.

Having 2FA enabled makes these accidents far less critical.

**Comment by tunnckoCore** [comment]
Agree. I was thinking about that issue last night.
You can send me an invite again, I have enabled 2fa for my account. :)

**Comment by bcoe** [comment]
@tunnckoCore done 👍

**Comment by tunnckoCore** [comment]
Thanks. :tada:
